### ISSUE TITLE
[Feature Request] Armor Blacklist or Anvil recipe to clear modifiers

### ISSUE THREAD

**Issue by Saereth** [spoorn/SpoornArmorAttributes#6]
Some recipes and more specifically buildings like minecolonies which use armors on armor stands cant recognize them because of the additional nbt data thast generates. Some anvil recipe to clear modifiers would be nice or a way to blacklist specific items from generasting with bonuses on the configs would be welcome. Enjoying the mod otherwise, thanks!

**Comment by spoorn** [comment]
Do you know why having NBT data on items would cause it to have issues with armor stands, recipes, or minecolonies?  That sounds like a bug for other mods - they shouldn't be assuming there's no custom NBT data on items.

You can use lapis lazuli to reroll items and remove modifiers, but the NBT hidden data will still be there.

I can add some logic to disable items from generating bonuses though

**Comment by spoorn** [comment]
How are they handling enchantments NBT data then?  Sure, I could add a check for `no_attribute` tag, or use a config disable list, but I'm still wondering how and why other mods would not work on my custom NBT data, but works on others.  If you open an issue on their end, could you link it here?

**Comment by Saereth** [comment]
Im pretty sure enchantment nbt will also invalidate their structure building, although I havent specifically tried it yet. Here's the issue though, https://github.com/ldtteam/minecolonies/issues/8506

**Comment by spoorn** [comment]
Even if you were able to disable certain items from having attribute NBT data on them, wouldn't you need to disable all armors you'd want to generate with minecolonies?  Seems like it could be a hassle, and if players wanted to actually wear those items, it wouldn't generate attributes anymore.  (Or did you mean you wanted some way to disable attribute generation for specific ItemStacks in your inventory, but that runs into this problem:)

I'd have to find a custom way to disable items from having attributes, without adding any NBT data to the item which I initially wanted to avoid as I'm trying to stick with the vanilla system as much as possible.

**Comment by Saereth** [comment]
in this instance minecolonies only uses vanilla leather, diamond and iron/gold armors. This is not a problem in my pack specifically since those all have 10 durability and exist only for decorations anyway, so a player would never wear them. In some other minecolonies pack for instance if direworlf 20 1.18 pack which has minecolonies was to add your mod they'd run into this issue as well. Then yeah they could presumably tag those specific vanilla armors not to generate attributes and let the modded armors in that pack continue generating them. 

Having a specific item stack not generate the stats could work but yeah I imagine that's a more complicated implementation

**Comment by Saereth** [comment]
Any update on this issue? If it's something you'd rather not implement I understand but as the pack is entering beta soon 
I'll have to resolve this by removing the mod most likely which would definitely be less preferable.

**Comment by Saereth** [comment]
I believe the issue https://github.com/spoorn/SpoornArmorAttributes/issues/8 is similar and raycom's PR (https://github.com/spoorn/SpoornArmorAttributes/pull/9)  submitted would address this nicely

**Comment by spoorn** [comment]
@Saereth I merged the PR from #9 , let me know if that mitigates your problem.  Haven't had time to look into a more permanent and proper solution

**Comment by Saereth** [comment]
yep this totally solves my issue, ty!
