### ISSUE TITLE
Feature Request: Disable Automatic Attributes

### ISSUE THREAD

**Issue by Raycoms** [spoorn/SpoornArmorAttributes#8]
Spoorn armor and tools have a problem with mods that use nbt for sorting and identification purposes.
I'd love a config setting that allows me to disable the automatic application of nbt data to tools and armor, and only do this in the smithing table.

**Comment by Raycoms** [comment]
This should just be a config check here: https://github.com/spoorn/SpoornArmorAttributes/blob/1.18/common/src/main/java/org/spoorn/spoornarmorattributes/mixin/ItemMixin.java#L22
right?

**Comment by spoorn** [comment]
merged, will release in next version
